
project_id = "hnrkipkckzosankwmlgx"

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false
